from pathlib import Path

from categorise.group_in_categories import rename_description, ALL_CATEGORIES
from data.clean_description import clean_all_descriptions
from data.date_utils import parse_date, filter_by_date_range, slice_by_period, Period
from data.read_data import read_bank_statements
from visualise.data_shaping import build_transaction_types_dicts, get_account_flows, AccountFlow, \
    get_account_flow_type_mask
from visualise.generate_graphs import (generate_transaction_types_bar_graph_per_period,
                                       generate_balance_bar_graph_per_period,
                                       generate_balance_graph,
                                       generate_transaction_types_bar_graph,
                                       generate_sub_category_line_graph_per_period,
                                       generate_grouped_bar_graph_per_period,
                                       generate_line_graph_account_flows_per_period,
                                       generate_line_graph_account_flows_categories_per_period)


def get_categorise_statements(start_date: str, end_date: str, bank_statement_path: Path):
    start_period = parse_date(start_date)
    end_period = parse_date(end_date)
    if end_period < start_period:
        raise ValueError("End date must be after start date.")
    bank_statements = filter_by_date_range(start_period, end_period, read_bank_statements(bank_statement_path))

    cleaned_statements = clean_all_descriptions(bank_statements)
    return rename_description(cleaned_statements)


def generate_income_sub_categories(sliced_statements: list) -> list:
    """
    Gets the list of sub categories for the category INCOME
    """
    income_subs = set()
    for df in sliced_statements:
        sub_mask = df['Category'] == "INCOME"
        income_subs.update(df.loc[sub_mask, 'Sub Category'])
    return sorted(income_subs)


def generate_expenses_categories(sliced_statements: list) -> list:
    """
    Gets the list of categories in Expenses
    """
    expenses_categories = set()
    for df in sliced_statements:
        sub_mask = (df["CAD$"] < 0) & (df["Category"].isin(ALL_CATEGORIES.keys()))
        expenses_categories.update(df.loc[sub_mask, 'Category'])
    return sorted(expenses_categories)


def get_monthly_statements(start_date: str, end_date: str, bank_statement_path: Path):
    categorised_statements = get_categorise_statements(start_date, end_date, bank_statement_path)
    return slice_by_period(categorised_statements, Period.MONTHS)


def get_transaction_types_dict(start_date: str, end_date: str, bank_statement_path: Path):
    categorised_statements = get_categorise_statements(start_date, end_date, bank_statement_path)
    return build_transaction_types_dicts(categorised_statements)


def generate_transaction_types_bar_graph_per_period_helper(start_date: str, end_date: str, bank_statement_path: Path):
    """
    Grouped bar chart of the 5 transaction types (expenses, income, misc, incoming_transfers,
    outgoing_transfers) one cluster per period.

        :param start_date: starting date of the period of the bank statements
        :param end_date: ending date of the period of the bank statements
        :param bank_statement_path: path of the bank statements
    """
    period_statements = get_monthly_statements(start_date, end_date, bank_statement_path)
    generate_transaction_types_bar_graph_per_period(period_statements)


def generate_balance_bar_graph_per_period_helper(start_date: str, end_date: str, bank_statement_path: Path):
    """
    WARNING: generate_period_summary_balance_bar_graph was generated by CLAUDE

    Grouped bar chart of Income vs Expenses per period, with each period's
    balance labeled above its cluster (red if negative).

        :param start_date: starting date of the period of the bank statements
        :param end_date: ending date of the period of the bank statements
        :param bank_statement_path: path of the bank statements
    """
    period_statements = get_monthly_statements(start_date, end_date, bank_statement_path)
    generate_balance_bar_graph_per_period(period_statements)


def generate_balance_pie_graph_helper(start_date: str, end_date: str, bank_statement_path: Path):
    """
    Income vs Expenses comparison, as a pie or bar chart. Net balance is shown
    below the chart, colored red if negative.

        :param start_date: starting date of the period of the bank statements
        :param end_date: ending date of the period of the bank statements
        :param bank_statement_path: path of the bank statements
    """
    generate_balance_graph(get_categorise_statements(start_date, end_date, bank_statement_path), "pie")


def generate_balance_bar_graph_helper(start_date: str, end_date: str, bank_statement_path: Path):
    """
    Income vs Expenses comparison, as a pie or bar chart. Net balance is shown
    below the chart, colored red if negative.

        :param start_date: starting date of the period of the bank statements
        :param end_date: ending date of the period of the bank statements
        :param bank_statement_path: path of the bank statements
    """
    generate_balance_graph(get_categorise_statements(start_date, end_date, bank_statement_path), "bar")


def generate_transaction_types_bar_graph_helper(start_date: str, end_date: str, bank_statement_path: Path):
    """
    Bar chart showing total $ for each of the 5 transaction types
    (Expenses, Income, Misc, Incoming/Outgoing Transfers).

        :param start_date: starting date of the period of the bank statements
        :param end_date: ending date of the period of the bank statements
        :param bank_statement_path: path of the bank statements
    """
    transaction_dict = get_transaction_types_dict(start_date, end_date, bank_statement_path)
    generate_transaction_types_bar_graph(transaction_dict)


def generate_grouped_bar_graph_per_period_helper(start_date: str, end_date: str, bank_statement_path: Path,
                                                 group: list, column="Sub Category"):
    """

    """
    period_statements = get_monthly_statements(start_date, end_date, bank_statement_path)
    generate_grouped_bar_graph_per_period(period_statements, group, column)


def generate_sub_category_line_graph_per_period_helper(start_date: str, end_date: str, bank_statement_path: Path,
                                                       sub_category: list):
    """

    """
    period_statements = get_monthly_statements(start_date, end_date, bank_statement_path)
    generate_sub_category_line_graph_per_period(period_statements, sub_category)


def generate_line_graph_account_flows_per_period_helper(start_date, end_date, bank_statement_path, expenses_excluded):
    period_statements = get_monthly_statements(start_date, end_date, bank_statement_path)
    account_flows = get_account_flows(period_statements,expenses_excluded)
    generate_line_graph_account_flows_per_period(period_statements, account_flows)


def generate_line_graph_account_flows_categories_per_period_helper(start_date, end_date, bank_statement_path,
                                                                   account_flow_type:AccountFlow, expenses_excluded):
    categorised_statements = get_categorise_statements(start_date, end_date, bank_statement_path)
    # Filter by account_flow_type before slicing by period
    statement_mask = get_account_flow_type_mask(categorised_statements, account_flow_type, expenses_excluded)
    statement = categorised_statements.loc[statement_mask]

    period_statements = slice_by_period(statement, Period.MONTHS)
    generate_line_graph_account_flows_categories_per_period(period_statements)


if __name__ == "__main__":
    script_dir = Path(__file__).resolve().parent.parent.parent
    bank_statement_path = script_dir / "data" / "RBC_download-transactions.csv"
    balance_path = script_dir / "data" / "RBC_Balance.csv"

    start_date = "01/01/2026"
    end_date = "30/09/2026"

    expenses_excluded = {"HOUSE_CLOTHING", "TRAVELS", "VANCOUVER_COMMUNITY_CENTER", "IMMIGRATION_AUSTRALIA", }
    generate_line_graph_account_flows_categories_per_period_helper(start_date, end_date, bank_statement_path,
                                                                   AccountFlow.EXPENSES, expenses_excluded)


    # generate_line_graph_account_flows_per_period_helper(start_date, end_date, bank_statement_path, expenses_excluded)


    # generate_balance_bar_graph_per_period_helper(start_date, end_date, bank_statement_path)
    # generate_transaction_types_bar_graph_per_period_helper(start_date, end_date, bank_statement_path)
    # generate_transaction_types_bar_graph_helper(start_date, end_date, bank_statement_path)
    # generate_balance_pie_graph_helper(start_date, end_date, bank_statement_path)
    # generate_balance_bar_graph_helper(start_date, end_date, bank_statement_path)

    # generate_sub_category_line_graph_per_period_helper(start_date, end_date, bank_statement_path, ["OXIO", "ALCOHOL", "SAFEWAY", "COSTCO", "LONDON DRUGS","HOUSE_CLOTHING", "TRAVELS", "VANCOUVER_COMMUNITY_CENTER", "IMMIGRATION_AUSTRALIA",])

    # sliced_statements = get_monthly_statements(start_date, end_date, bank_statement_path)
    # income = generate_income_sub_categories(sliced_statements)
    # generate_grouped_bar_graph_per_period_helper(start_date, end_date, bank_statement_path, income)

    # sliced_statements = get_monthly_statements(start_date, end_date, bank_statement_path)
    # expenses = generate_expenses_categories(sliced_statements)
    # exclude = {"HOUSE_CLOTHING", "TRAVELS", "VANCOUVER_COMMUNITY_CENTER", "IMMIGRATION_AUSTRALIA", }
    # vital_expenses = list(set(expenses) - exclude)
    # generate_grouped_bar_graph_per_period_helper(start_date, end_date, bank_statement_path, expenses, "Category")
