from pathlib import Path

from categorise.group_in_categories import rename_description
from data.clean_description import clean_all_descriptions
from data.date_utils import parse_date, filter_by_date_range, slice_by_period, Period
from data.read_data import read_bank_statements
from visualise.data_shaping import build_transaction_types_dicts
from visualise.generate_graphs import (generate_transaction_types_bar_graph_per_period,
                                       generate_balance_bar_graph_per_period,
                                       generate_balance_graph,
                                       generate_transaction_types_bar_graph, generate_sub_category_bar_graph_per_period,
                                       generate_sub_category_line_graph_per_period)


def get_categorise_statements(start_date: str, end_date: str, bank_statement_path: Path):
    start_period = parse_date(start_date)
    end_period = parse_date(end_date)
    bank_statements = filter_by_date_range(start_period, end_period, read_bank_statements(bank_statement_path))

    cleaned_statements = clean_all_descriptions(bank_statements)
    return rename_description(cleaned_statements)


def get_monthly_statements(start_date: str, end_date: str, bank_statement_path: Path):
    categorised_statements = get_categorise_statements(start_date, end_date, bank_statement_path)
    return slice_by_period(categorised_statements, Period.MONTHS)


def get_transaction_types_dict(start_date: str, end_date: str, bank_statement_path: Path):
    categorised_statements = get_categorise_statements(start_date, end_date, bank_statement_path)
    return build_transaction_types_dicts(categorised_statements)


def generate_transaction_types_bar_graph_per_period_helper(start_date: str, end_date: str, bank_statement_path: Path):
    """
    Grouped bar chart of the 5 transaction types (expenses, income, misc, incoming_transfers,
    outgoing_transfers) one cluster per period.

        :param start_date: starting date of the period of the bank statements
        :param end_date: ending date of the period of the bank statements
        :param bank_statement_path: path of the bank statements
    """
    period_statements = get_monthly_statements(start_date, end_date, bank_statement_path)
    generate_transaction_types_bar_graph_per_period(period_statements)


def generate_balance_bar_graph_per_period_helper(start_date: str, end_date: str, bank_statement_path: Path):
    """
    WARNING: generate_period_summary_balance_bar_graph was generated by CLAUDE

    Grouped bar chart of Income vs Expenses per period, with each period's
    balance labeled above its cluster (red if negative).

        :param start_date: starting date of the period of the bank statements
        :param end_date: ending date of the period of the bank statements
        :param bank_statement_path: path of the bank statements
    """
    period_statements = get_monthly_statements(start_date, end_date, bank_statement_path)
    generate_balance_bar_graph_per_period(period_statements)


def generate_balance_pie_graph_helper(start_date: str, end_date: str, bank_statement_path: Path):
    """
    Income vs Expenses comparison, as a pie or bar chart. Net balance is shown
    below the chart, colored red if negative.

        :param start_date: starting date of the period of the bank statements
        :param end_date: ending date of the period of the bank statements
        :param bank_statement_path: path of the bank statements
    """
    generate_balance_graph(get_categorise_statements(start_date, end_date, bank_statement_path), "pie")


def generate_balance_bar_graph_helper(start_date: str, end_date: str, bank_statement_path: Path):
    """
    Income vs Expenses comparison, as a pie or bar chart. Net balance is shown
    below the chart, colored red if negative.

        :param start_date: starting date of the period of the bank statements
        :param end_date: ending date of the period of the bank statements
        :param bank_statement_path: path of the bank statements
    """
    generate_balance_graph(get_categorise_statements(start_date, end_date, bank_statement_path), "bar")


def generate_transaction_types_bar_graph_helper(start_date: str, end_date: str, bank_statement_path: Path):
    """
    Bar chart showing total $ for each of the 5 transaction types
    (Expenses, Income, Misc, Incoming/Outgoing Transfers).

        :param start_date: starting date of the period of the bank statements
        :param end_date: ending date of the period of the bank statements
        :param bank_statement_path: path of the bank statements
    """
    transaction_dict = get_transaction_types_dict(start_date, end_date, bank_statement_path)
    generate_transaction_types_bar_graph(transaction_dict)


def generate_sub_category_bar_graph_per_period_helper(start_date: str, end_date: str, bank_statement_path: Path,
                                                      sub_category: list):
    """

    """
    period_statements = get_monthly_statements(start_date, end_date, bank_statement_path)
    generate_sub_category_bar_graph_per_period(period_statements, sub_category)


def generate_sub_category_line_graph_per_period_helper(start_date: str, end_date: str, bank_statement_path: Path,
                                                      sub_category: list):
    """

    """
    period_statements = get_monthly_statements(start_date, end_date, bank_statement_path)
    generate_sub_category_line_graph_per_period(period_statements, sub_category)


if __name__ == "__main__":
    script_dir = Path(__file__).resolve().parent.parent.parent
    bank_statement_path = script_dir / "data" / "RBC_download-transactions.csv"

    # generate_balance_bar_graph_per_period_helper("01/04/2026", "01/08/2026", bank_statement_path)
    # generate_transaction_types_bar_graph_per_period_helper("01/04/2026", "01/08/2026", bank_statement_path)
    # generate_transaction_types_bar_graph_helper("01/04/2026", "01/08/2026", bank_statement_path)
    # generate_balance_pie_graph_helper("01/04/2026", "01/08/2026", bank_statement_path)
    # generate_balance_bar_graph_helper("01/04/2026", "01/08/2026", bank_statement_path)
    # generate_sub_category_bar_graph_per_period_helper("01/01/2026", "01/08/2026", bank_statement_path, ["OXIO", "ALCOHOL", "SAFEWAY", "COSTCO", "LONDON DRUGS"])
    generate_sub_category_line_graph_per_period_helper("01/01/2026", "01/08/2026", bank_statement_path, ["OXIO", "ALCOHOL", "SAFEWAY", "COSTCO", "LONDON DRUGS"])
